server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instanceId: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    metadata-map:
      description: common service ,count service
spring:
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: ${rabbitmq.virtual-host}
  datasource:
    driver-class-name: ${mysql.driver-class-name}
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  zipkin:
    base-url: http://192.168.187.129:9411
  sleuth:
    sampler:
      probability: 1.0
# 计数服务每个hash存储的条数
count:
  bucket:
    size: 10000000
