server:
  port: 9000
spring:
  application:
    name: fly-sso
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0
# 自定义配置
fly:
  sso:
    # 网关地址
    gateway_url: http://127.0.0.1:9001/
    # 跳转地址
    redirect_url:
      fly_web: http://localhost:8089/
      fly_admin: http://localhost:8090/
