server:
  port: 8761
eureka:
  client:
    healthCheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://panzi:123456@localhost:${server.port}/eureka
spring:
  security:
    user:
      name: panzi
      password: 123456