server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: false
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://panzi:123456@eureka2:8762/eureka/,http://panzi:123456@eureka1:8761/eureka/
    register-with-eureka: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    fetch-registry: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
