server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.187.129
    hostname: 192.168.187.129
  client:
    service-url:
      defaultZone: http://panzi:123456@192.168.187.130:8761/eureka/
    register-with-eureka: true
    instanceId: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    fetch-registry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
