server:
  port: 8001
spring:
  application:
    name: fly-base-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://panzi:123456@eureka1:8761/eureka/,http://panzi:123456@eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      description: base service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0