server:
  port: 8001
spring:
  application:
    name: fly-base-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://panzi:123456@192.168.187.129:8761/eureka/,http://panzi:123456@192.168.187.130:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${server.port}
    metadata-map:
      description: base service
  zipkin:
    base-url: http://192.168.187.129:9411
  sleuth:
    sampler:
      probability: 1.0